[package]
name = "genesoxide-test-harness"
version = "0.1.0"
edition = "2024"

[dependencies]
genesoxide-core = { path = "../genesoxide-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1"
hound = "3.5"
soundlog = "=0.10.0"

[dev-dependencies]
proptest = "1"
claxon = "0.4"

[build-dependencies]
cc = "1"
